// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UploadView is the wire form of an upload in a list or detail response. It
 * carries identity and live progress only — never a source path or secret.
 */
export interface UploadView {
    "id": string;
    "filename": string;
    "size": number;
    "status": string;
    "bytesDone": number;
    "curBps": number;
    "avgBps": number;
    "etaSeconds": number;
    "error"?: string;
    "updatedAt": number;
}
