// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as common$0 from "../../../../../code.sli.ke/go/vega/packages/common/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "upload.event": common$0.Event;
        }
    }
}
