// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Event is a fact the engine publishes for controllers (the UI, the CLI, logs)
 * to observe. It is best-effort telemetry, never a command channel.
 */
export interface Event {
    /**
     * e.g. "upload.created", "progress", "upload.completed"
     */
    "Kind": string;

    /**
     * "" for engine-wide events
     */
    "UploadID": UploadID;

    /**
     * unix seconds
     */
    "At": number;

    /**
     * small, JSON-friendly payload
     */
    "Fields": { [_ in string]?: any } | null;
}

/**
 * Typed IDs. They are plain strings so they cross SQLite and the wire without
 * conversion, but the distinct types stop us from passing an UploadID where a
 * SessionID is wanted.
 */
export type UploadID = string;
