// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UploadService is the desktop app's controller over the uploader daemon. Every
 * method is a thin call across the daemon's Unix socket, so the UI holds no
 * upload state of its own: close the window and uploads keep running, reopen it
 * and List reattaches to the same daemon. The leading context.Context on each
 * method is injected by Wails and never appears in the generated JS signature.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ipc$0 from "../../packages/ipc/models.js";

export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(204361422, id);
}

export function Enqueue(path: string): $CancellablePromise<string> {
    return $Call.ByID(2352636246, path);
}

export function List(): $CancellablePromise<ipc$0.UploadView[] | null> {
    return $Call.ByID(4009003924);
}

export function Metrics(): $CancellablePromise<{ [_ in string]?: number } | null> {
    return $Call.ByID(2915716193);
}

export function Pause(id: string): $CancellablePromise<void> {
    return $Call.ByID(2852225638, id);
}

export function Resume(id: string): $CancellablePromise<void> {
    return $Call.ByID(2591327119, id);
}
